INC_DIR= ../../include
LIB_DIR= ../../lib
BIN_DIR= ../../bin

LDFLAG=-pthread -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lxml2 -lglib-2.0 -L/usr/X11R6/lib -L/usr/local/lib -L$(LIB_DIR)
LIBS= -lARgsub -lARvideo -lAR -lpthread -lglut -lGLU -lGL -lXi -lX11 -lm -lach
CFLAG= -O -pthread -I/usr/include/gstreamer-0.10 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libxml2 -I/usr/X11R6/include -g -I$(INC_DIR)

OBJS = marker.o
HEADERS = marker.h

all: $(BIN_DIR)/detectMarker

$(BIN_DIR)/detectMarker: detectMarker.o $(OBJS)
	g++ -o $(BIN_DIR)/detectMarker detectMarker.o $(OBJS) $(LIBS) $(LDFLAG)

detectMarker.o: detectMarker.c $(HEADERS)
	g++ -c $(CFLAG) detectMarker.c

marker.o: marker.c $(HEADERS)
	g++ -c $(CFLAG) marker.c

clean:
	rm -f *.o
	rm -f $(BIN_DIR)/detectMarker

allclean:
	rm -f *.o
	rm -f $(BIN_DIR)/detectMarker
	rm -f Makefile
